#pragma once

#include <vector>
#include <array>
#include <map>
#include <set>
#include <list>
#include <stack>
#include <queue>
#include <deque>
#include <unordered_map>
#include <unordered_set>
#include <functional>
#include <string>
#include <sstream>
#include <fstream>
#include <memory>
#include <algorithm>
#include <iostream>
#include <filesystem>
#include <typeindex>
#include <math.h>